version: 3

tasks:
  up:
    desc: Start the database
    cmds:
      - docker compose up -d database
      - ./docker/database/wait_for_it.sh
    aliases:
      - u

  stop:
    aliases:
      - s
    cmds:
      - docker compose stop database
    desc: Stop the database

  migrate:
    desc: Run database migrations
    cmds:
      - docker compose run --rm demo bin/console doctrine:migrations:migrate --no-interaction
    aliases:
      - m
