version: "3"

silent: true

includes:
  database:
    taskfile: ./taskfiles/database.yaml
    aliases: [db]
  dependencies:
    taskfile: ./taskfiles/dependencies.yaml
    aliases: [d]
  run:
    taskfile: ./taskfiles/run.yaml
    aliases: [r]
  tests:
    taskfile: ./taskfiles/tests.yaml
    aliases: [t]

tasks:
  default:
    cmds:
      - task --list
