version: '3'

silent: true

tasks:
  default:
    cmds:
      - task --list

  app:dependencies:install:
    desc: Install project dependencies
    cmds:
      - docker compose run --rm php composer install --prefer-dist --optimize-autoloader --no-interaction
    aliases:
      - a:d:i

  app:dependencies:update:
    desc: Update project dependencies
    cmds:
      - docker compose run --rm php composer update --prefer-dist --optimize-autoloader --no-interaction
    aliases:
      - a:d:u

  app:tests:unit:
    desc: Run unit tests
    cmds:
      - docker compose run --rm php bin/phpunit --testsuite "Unit Tests" --testdox
    aliases:
      - a:t:u

  app:tests:acceptance:
    desc: Run acceptance tests
    cmds:
      - docker compose run --rm php bin/phpunit --testsuite "Acceptance Tests" --testdox
    aliases:
      - a:t:a

  app:tests:integration:
    desc: Run integration tests
    cmds:
      - docker compose run --rm php bin/phpunit --testsuite "Integration Tests" --testdox
    aliases:
      - a:t:i

  app:tests:end-to-end:
    desc: Run end-to-end tests
    cmds:
      - docker compose run --rm php bin/phpunit --testsuite "End-to-End Tests" --testdox
    aliases:
      - a:t:e

  app:tests:
    desc: Run all tests
    cmds:
      - task: a:t:u
      - task: a:t:a
      - task: a:t:i
      - task: a:t:e
    aliases:
      - a:t

  database:start:
    desc: Start the database
    cmds:
      - docker compose up -d database
      - ./docker/database/wait_for_it.sh
    aliases:
      - db:start

  database:stop:
    desc: Stop the database
    cmds:
      - docker compose stop database
    aliases:
      - db:stop

  docker:down:
    desc: Stop all Docker containers and clean volumes
    cmds:
      - docker compose down -v --remove-orphans
    aliases:
      - d:d
